baseURL: "https://www.honda-ds.github.io/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Honda Data"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Honda Data"
  description: "Data-driven decision making. Find opportunities, increase revenue, mitigate risk"
  images: 
    - "images/logo.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    telegram: "https://t.me/hugohondaf"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "Brazil"

  contact:
    - "honda.data.science [at] gmail.com"

  copyright: "© 2023 Honda Data. All Rights Reserved"

  postProcess: false

menus:
  main:
    # - name: "Início"
    #   url: "#"
    #   weight: 1

    - name: "Services"
      url: "/#services"
      weight: 1

    - name: "Our work"
      url: "/#portfolio"
      weight: 2

    # - name: "Sobre nós"
    #   url: "/#cta"
    #   weight: 3

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  buttons:
    - name: "Contact"
      url: "/#cta"
      weight: 5
      pre: "btn btn-primary text-light"

  # footer:
  #   - name: "Home"
  #     url: "/#hero"
  #     weight: 1

  #   - name: "How we work"
  #     url: "/#"
  #     weight: 2

  #   - name: "Our team"
  #     url: "/#"
  #     weight: 3

  #   - name: "Pricing"
  #     url: "/#"
  #     weight: 4

  #   - name: "Blog"
  #     url: "/blog"
  #     weight: 5

taxonomies:
  series: "series"
  tags: "tags"
